<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.palladiosimulator.blockchainsystems</groupId>
        <artifactId>org.palladiosimulator.blockchainsystems</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>target-platform</artifactId>
    <packaging>eclipse-target-definition</packaging>

    <repositories>
        <repository>
            <id>eclipse-platform</id>
            <url>https://download.eclipse.org/releases/2024-12</url>
            <layout>p2</layout>
        </repository>
        <repository>
            <id>palladio-simulator</id>
            <url>https://updatesite.palladio-simulator.com/palladio-build-updatesite/nightly/</url>
            <layout>p2</layout>
        </repository>
    </repositories>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-maven-plugin</artifactId>
                <version>${tycho.version}</version>
                <extensions>true</extensions>
            </plugin>

            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>target-platform-configuration</artifactId>
                <version>${tycho.version}</version>
                <configuration>
                    <target>
                        <file>../target-platform/target-platform.target</file>
                    </target>
                    <pomDependencies>consider</pomDependencies>
                    <environments>
                        <environment>
                            <os>linux</os>
                            <ws>gtk</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>win32</os>
                            <ws>win32</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>macosx</os>
                            <ws>cocoa</ws>
                            <arch>x86_64</arch>
                        </environment>
                    </environments>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
